### ISSUE TITLE
E2E: `TokenDeleteTransaction`

### ISSUE THREAD

**Issue by ivaylogarnev-limechain** [hashgraph/hedera-sdk-tck#245] opened 2024-09-17 13:04 UTC
```[tasklist]
### Tasks
- [ ]  Implement E2E `TokenDeleteTransaction` tests specified in the documentation added by https://github.com/hashgraph/hedera-sdk-tck/issues/142.
```

**Comment by rwalworth** [comment] 2024-09-18 17:30
What is this issue meant to track? It seems like it's maybe a duplicate of either #143 or #243.

**Closed** 2024-10-07 05:28 UTC

**Comment by ivaylogarnev-limechain** [comment] 2024-10-07 05:29
> What is this issue meant to track? It seems like it's maybe a duplicate of either #143 or #243.

I apologize for the oversight. It looks like this issue is indeed a duplicate of either #143 or #243. I hadn't noticed those earlier, but thank you for pointing it out. I'll go ahead and close this one to avoid any redundancy.

**Comment by rwalworth** [comment] 2024-10-07 15:05
> > What is this issue meant to track? It seems like it's maybe a duplicate of either #143 or #243.
> 
> I apologize for the oversight. It looks like this issue is indeed a duplicate of #143 I hadn't noticed those earlier, but thank you for pointing it out. I'll go ahead and close this one to avoid any redundancy.

No worries!
